version: "3.8"

services:
  appserver:
    user: root
    container_name: appserver
    build: .
    depends_on:
      - mysqlserver
      - redisserver
    command: ["bin/wait-for-it.sh mysqlserver:3306 -t 120 && jboss-eap-7.2/bin/standalone.sh"] 
    expose:
      - "6789"  
    ports:
      #- DEFINIR AS PORTAS DO SERVIDOR  
      - "6789:8080"
      - "8080:8080"
      #- "9990:9990"
      #- "8787:8787"
    environment:
      TZ: "America/Sao_Paulo"
      JBOSS_USER: "root"
      JAVA_OPTS: "%JAVA_OPTS% -Xms1024m -Xmx3072m"
    volumes:
      - log-volume:/var/log
      - tmp-volume:/var/tmp/siga
    networks:
      - siga

  mysqlserver:
    container_name: mysqlserver
    image: mysql:8.0.21
    restart: always
    expose:
      - "3306"
    ports:
      - 5001:3306
    environment:
      TZ: "America/Sao_Paulo"
      MYSQL_ROOT_PASSWORD: "siga"
      MYSQL_ROOT_HOST: "%"
    volumes:
     - ./mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - siga
    #   - mysql-volume:/var/lib/mysql

  assijus:
    build: ./assijus
    ports:
      - "8280:8080"
      - "8243:8443"

    volumes:
      - log-volume01:/var/log
    links:
      - bluc
    environment:
      PROP_ASSIJUS_REDIS_MASTER_HOST: redisserver
      PROP_ASSIJUS_REDIS_MASTER_PORT: 6379
      PROP_ASSIJUS_REDIS_SLAVE_HOST:
      PROP_ASSIJUS_REDIS_SLAVE_PORT:
      PROP_ASSIJUS_REDIS_PASSWORD: ***RANDOM_GUID_REDIS***
      PROP_ASSIJUS_REDIS_DATABASE: 1
      PROP_ASSIJUS_BLUCSERVICE_URL: http://bluc:8080/blucservice/api/v1
      PROP_ASSIJUS_POPUP_URLS: https://sigadoc.riopreto.sp.gov.br
      PROP_ASSIJUS_SYSTEMS: siga
      PROP_ASSIJUS_TESTSIGNER_URL: http://testsigner:8080/testsigner/api/v1
      PROP_ASSIJUS_TESTSIGNER_PASSWORD: ***RANDOM_GUID_TESTSIGNER***
      PROP_ASSIJUS_TIMESTAMP_PUBLIC_KEY: ***RANDOM_GUID***
      PROP_ASSIJUS_TIMESTAMP_PRIVATE_KEY: ***RANDOM_GUID***
    networks:
      - siga
      
  bluc:
    build: ./blucservice
    ports:
      - "5003:8080"
    volumes:
      - log-volume01:/var/log
    networks:
      - siga

  testsigner:
    build: ./testsigner
    ports:
      - "5004:8080"
    volumes:
      - log-volume01:/var/log
    environment:
      PROP_TESTSIGNER_PASSWORD: ***RANDOM_GUID_TESTSIGNER***
    networks:
      - siga

  redisserver:
    container_name: redisserver
    command: redis-server --requirepass ***RANDOM_GUID_REDIS***
    image: redis:alpine
    expose:
      - "6379"
    ports:
      - 5002:6379
    networks:
      - siga

volumes:
  log-volume: {}
  log-volume01: {}
  tmp-volume: {}
  mysql-volume: {}

networks:
  siga:
